version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: oxford-erp-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: oxford-erp
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - oxford-erp-network

  # Redis for caching and sessions
  redis:
    image: redis:7.2-alpine
    container_name: oxford-erp-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - oxford-erp-network

  # Backend API Server
  api:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: oxford-erp-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:${MONGO_ROOT_PASSWORD}@mongodb:27017/oxford-erp?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      JWT_SECRET: ${JWT_SECRET}
      WHATSAPP_API_TOKEN: ${WHATSAPP_API_TOKEN}
      WHATSAPP_PHONE_NUMBER_ID: ${WHATSAPP_PHONE_NUMBER_ID}
      WHATSAPP_WEBHOOK_VERIFY_TOKEN: ${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      CLIENT_URL: ${CLIENT_URL}
    volumes:
      - api_uploads:/app/uploads
      - api_logs:/app/logs
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    networks:
      - oxford-erp-network

  # Frontend Application
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${API_BASE_URL}
        VITE_SOCKET_URL: ${SOCKET_URL}
        VITE_WHATSAPP_API_TOKEN: ${WHATSAPP_API_TOKEN}
    container_name: oxford-erp-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - oxford-erp-network

  # Nginx Load Balancer (for production scaling)
  nginx:
    image: nginx:alpine
    container_name: oxford-erp-nginx
    restart: unless-stopped
    volumes:
      - ./nginx-lb.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - frontend
      - api
    networks:
      - oxford-erp-network

volumes:
  mongodb_data:
  redis_data:
  api_uploads:
  api_logs:

networks:
  oxford-erp-network:
    driver: bridge